# -*- mode: python ; coding: utf-8 -*-
"""
Analyze_Session.spec — PyInstaller specification for the post-session analyzer.
Generated by build.py. Built as a console app so users can see the report.
"""

block_cipher = None

a = Analysis(
    ['analyze_diagnostics.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        "src.diagnostics",
        "src.diagnostics.analyzer",
        "tomllib",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib', 'numpy', 'pandas', 'PIL',
        'PyQt5', 'PyQt6', 'PySide2', 'PySide6',
        'IPython', 'jupyter', 'pytest',
        # The analyzer doesn't need pygame, tkinter, or pythonosc
        'pygame', 'tkinter', 'pythonosc',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Analyze_Session',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,                    # console app — user sees the report
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='Analyze_Session',
)
